/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package project;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Gabriel
 */
public class ChooserAntennaJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ChooserAntennaJDialog
     */
    private String antennaType;
    private String filePath;

    public ChooserAntennaJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setDefaultCloseOperation(javax.swing.JDialog.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        aReceiverBeastRButton = new javax.swing.JRadioButton();
        aEmulatorRButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        startButton.setText("Start");
        startButton.setToolTipText("");
        startButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        aReceiverBeastRButton.setSelected(true);
        aReceiverBeastRButton.setText("Antenna Receiver Beast");
        aReceiverBeastRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aReceiverBeastRButtonActionPerformed(evt);
            }
        });

        aEmulatorRButton.setText("Antenna Emulator");
        aEmulatorRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aEmulatorRButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(aReceiverBeastRButton)
                        .addGap(44, 44, 44)
                        .addComponent(aEmulatorRButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(startButton)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aReceiverBeastRButton)
                    .addComponent(aEmulatorRButton))
                .addGap(18, 18, 18)
                .addComponent(startButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        if(aReceiverBeastRButton.isSelected()){
            try {
                this.antennaType = "Beast";
            } catch (Exception e) {
            }
        } else if(aEmulatorRButton.isSelected()){
            System.out.println("Emulatorrasdasd");
            this.antennaType = "Emulator";
            JFileChooser jFileChooser = new JFileChooser();
            String rootPath = System.getProperty("user.dir");
            File rootFile = new File(rootPath+"/src/resources/tracks/");
            jFileChooser.setCurrentDirectory(rootFile);
            jFileChooser.showDialog(this, "Choose");
            File file = jFileChooser.getSelectedFile();
            
            this.filePath=file.getPath();
        }
        this.dispose(); //???
    }//GEN-LAST:event_startButtonActionPerformed

    private void aReceiverBeastRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aReceiverBeastRButtonActionPerformed
        if(aReceiverBeastRButton.isSelected()){
            aEmulatorRButton.setSelected(false);
        }
    }//GEN-LAST:event_aReceiverBeastRButtonActionPerformed

    private void aEmulatorRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aEmulatorRButtonActionPerformed
        if(aEmulatorRButton.isSelected()){
            aReceiverBeastRButton.setSelected(false);
        }
    }//GEN-LAST:event_aEmulatorRButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooserAntennaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooserAntennaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooserAntennaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooserAntennaJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChooserAntennaJDialog dialog = new ChooserAntennaJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
            public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getAntennaType() {
        return antennaType;
    }

    public void setAntennaType(String antennaType) {
        this.antennaType = antennaType;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aEmulatorRButton;
    private javax.swing.JRadioButton aReceiverBeastRButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
